meta:
  cf:
    domain: (( merge ))
    nats_servers: (( merge ))

jobs:
- name: api
  templates:
  - <<: (( merge ))
  - name: route-registrar
    release: route-registrar
  networks: (( merge ))
  resource_pool: (( merge ))
  persistent_disk: (( merge ))
  instances: (( merge ))
  update: (( merge ))
  properties:
    <<: (( merge ))
    route_registrar:
      external_host: (( "logs." meta.cf.domain ))
      external_ip: (( jobs.api.networks.ls1.static_ips.[0] ))
      port: 5601
      message_bus_servers: (( meta.cf.nats_servers ))
      health_checker:
        name: warden-test
- <<: (( merge ))
